name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        environment:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=gymapidb

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:e2e
        env:
          NODE_ENV: "test"
          JWT_SECRET: "jwt-secret"
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/gymapidb?schema=public"
